### ISSUE TITLE
It doesn't work on CakePHP v3.6

### ISSUE THREAD

**Issue by lbassuncao** [dereuromark/cakephp-cache#14]
2019-07-13 22:54:16 Error: [ArgumentCountError] Too few arguments to function Cache\Routing\Middleware\CacheMiddleware::__invoke(), 2 passed in /home/csm/Projects/Local/PFN_BS4/vendor/dereuromark/cakephp-cache/src/Routing/Middleware/CacheMiddleware.php on line 57 and exactly 3 expected

**Comment by dereuromark** [comment]
Can u make a PR to fix things?

**Comment by lbassuncao** [comment]
Certainly I can try. But I'm novice using Cake.

**Comment by dereuromark** [comment]
This actually sounds more like a user error. Please check how you are calling this in your Application class - and refer to the docs on how this should be (both core and plugin docs).

Can you maybe also post that here?
